server:
  host: '0.0.0.0'
  port: 8080
db:
  host: localhost
  port: 3306
  user: sqluser
  pass: P@ssw0rd
  dbName: web39
  table: tasks
cache:
  host: cache.example.com
  port: 6379
smtp:
  host: smtp.example.com
  port: 25
  sender: sender@yourdomain.com
  